volumes:
  db: {}

networks:
  server_proxy:
    external: true
 
services: 
  app: 
    build: .
    command: [ "-dsn", "/root/tdispo.db", "-session-key", "${session_key}", "-logo", "pcbb.png" ]
    volumes:
      - db:/root
    networks:
      - server_proxy
    labels: 
      - traefik.enable=true 
      - traefik.http.routers.tdispo_secure.rule=Host(`${url}`)
      - traefik.http.routers.tdispo_secure.entrypoints=websecure
      - traefik.http.routers.tdispo_secure.tls=true
      - traefik.http.routers.tdispo_secure.tls.certresolver=letsencrypt
      - traefik.http.middlewares.tdispo_auth.basicauth.users=pcbb:${basic_auth}
      - traefik.http.routers.tdispo_secure.middlewares=tdispo_auth

      - ghosts.auth=true
      - ghosts.host=${url}
      - ghosts.category=~Applications
      - ghosts.proto=https

  litestream:
    image: litestream/litestream
    command: [ "replicate" ]
    working_dir: /data
    depends_on:
      - app
    volumes:
      - ./litestream.yml:/etc/litestream.yml
      - db:/data
    environment:
      - LITESTREAM_KEY_ID=${litestream_key_id}
      - LITESTREAM_ACCESS_KEY=${litestream_access_key}
      - LITESTREAM_BUCKET=${litestream_bucket}
      - LITESTREAM_ENDPOINT=${litestream_endpoint}
