volumes:
  db: {}
 
services: 
  app: 
    build: .
    command: [ "-dsn", "/root/tdispo.db", "-session-key", "${session_key}", "-logo", "pcbb.png" ]
    volumes:
      - db:/root
    labels: 
      - traefik.enable=true 
      - traefik.http.middlewares.auth.basicauth.users=pcbb:${basic_auth}
      - traefik.http.routers.nginx.rule=Host(`${url}`)
      - traefik.http.routers.nginx.entrypoints=websecure

  litestream:
    image: litestream/litestream
    command: [ "replicate" ]
    working_dir: /data
    depends_on:
      - app
    volumes:
      - ./litestream.yml:/etc/litestream.yml
      - db:/data
    environment:
      - LITESTREAM_KEY_ID=${litestream_key_id}
      - LITESTREAM_ACCESS_KEY=${litestream_access_key}
      - LITESTREAM_BUCKET=${litestream_bucket}
      - LITESTREAM_ENDPOINT=${litestream_endpoint}
